spring.application.name=gateway
server.port=8082
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
eureka.client.instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.instance.lease-renewal-interval-in-seconds=5